name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required dependencies
      run: sudo apt-get install git cmake gcc g++ libjansson-dev libcurl4-openssl-dev libssl-dev libgmp-dev ocl-icd-opencl-dev

    - name: Install CUDA toolkit
      run: sudo apt-get install gcc-6 g++-6 nvidia-cuda-toolkit
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 10
           sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20

           sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
           sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20

           sudo update-alternatives --config gcc
           sudo update-alternatives --config g++

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


      
